package ca.bc.gov.educ.studentdatacollection.api.constants;

/**
 * The enum Event type.
 */
public enum EventType {
  VALIDATE_SDC_STUDENT,
  PROCESS_PEN_MATCH,
  PROCESS_PEN_MATCH_RESULTS,
  READ_FROM_TOPIC,
  INITIATED,
  MARK_SAGA_COMPLETE,
  GET_PAGINATED_SCHOOLS,
  WRITE_ENROLLED_PROGRAMS,
  CALCULATE_ADDITIONAL_STUDENT_ATTRIBUTES
}
