package ca.bc.gov.educ.studentdatacollection.api.constants;

/**
 * The enum Event outcome.
 */
public enum EventOutcome {
  STUDENT_PROCESSED,
  EMAIL_SENT,
  PEN_MATCH_PROCESSED,
  GRAD_STATUS_FETCHED,
  GRAD_STATUS_RESULTS_PROCESSED,
  PEN_MATCH_RESULTS_PROCESSED,
  READ_FROM_TOPIC_SUCCESS,
  INITIATE_SUCCESS,
  SAGA_COMPLETED,
  ENROLLED_PROGRAMS_WRITTEN,
  ADDITIONAL_STUDENT_ATTRIBUTES_CALCULATED,
  PROVINCE_DUPLICATE_PROCESSED,
  NEW_COLLECTION_CREATED,
  STUDENTS_DEMOG_UPDATED,
  CLOSURE_NOTIFICATIONS_DISPATCHED,
  STUDENT_FOUND,
  STUDENT_UPDATED,
  SDC_STUDENT_STATUS_UPDATED,
  MERGE_FOUND,
  FUNDING_GROUP_SNAPSHOT_SAVED
}
