package ca.bc.gov.educ.studentdatacollection.api.constants;

/**
 * The enum Event type.
 */
public enum EventType {
  PROCESS_SDC_STUDENT,
  PROCESS_PEN_MATCH,
  FETCH_GRAD_STATUS,
  PROCESS_GRAD_STATUS_RESULT,
  PROCESS_PEN_MATCH_RESULTS,
  READ_FROM_TOPIC,
  INITIATED,
  MARK_SAGA_COMPLETE,
  GET_PAGINATED_SCHOOLS,
  WRITE_ENROLLED_PROGRAMS,
  CALCULATE_ADDITIONAL_STUDENT_ATTRIBUTES,
  PROCESS_PROVINCE_DUPLICATE,
  SEND_EMAIL,
  CLOSE_CURRENT_COLLECTION_AND_OPEN_NEW_COLLECTION,
  SEND_CLOSURE_NOTIFICATIONS,
  UPDATE_STUDENTS_DEMOG_DOWNSTREAM,
  GET_STUDENT,
  UPDATE_STUDENT,
  UPDATE_SDC_STUDENT_STATUS,
  GET_MERGES
}
