package ca.bc.gov.educ.studentdatacollection.api.constants;

public enum SagaTopicsEnum {

  SDC_BATCH_STUDENT_PROCESSING_TOPIC,
  SDC_BATCH_NEW_PEN_PROCESSING_TOPIC,
  SDC_BATCH_USER_MATCH_PROCESSING_TOPIC,
  SDC_BATCH_USER_UNMATCH_PROCESSING_TOPIC,
  PEN_MATCH_API_TOPIC,
  STUDENT_API_TOPIC,
  PEN_SERVICES_API_TOPIC,
  SDC_API_TOPIC
}
