package ca.bc.gov.educ.studentdatacollection.api.constants;

public enum SagaEnum {

  INDY_SCHOOLS_NO_ACTIVITY_EMAIL_SAGA,
  INDY_SCHOOLS_NOT_SUBMITTED_EMAIL_SAGA,
  STUDENT_DATA_COLLECTION_STUDENT_PROCESSING_SAGA,
  PROVINCE_DUPLICATE_PROCESSING_SAGA,
  CLOSE_COLLECTION_SAGA,
  UPDATE_STUDENT_DOWNSTREAM_SAGA
}
