package ca.bc.gov.educ.studentdatacollection.api.constants;


public enum TopicsEnum {
  STUDENT_DATA_COLLECTION_API_TOPIC,
  STUDENT_DATA_COLLECTION_POST_SAGA_TOPIC,
  STUDENT_DATA_COLLECTION_PROCESS_STUDENT_SAGA_TOPIC,
  INDY_SCHOOLS_NO_ACTIVITY_EMAIL_SAGA_TOPIC,
  INDY_SCHOOLS_NOT_SUBMITTED_EMAIL_SAGA_TOPIC,
  PEN_MATCH_API_TOPIC,
  GRAD_STUDENT_API_FETCH_GRAD_STATUS_TOPIC,
  INSTITUTE_API_TOPIC,
  PROVINCE_DUPLICATE_PROCESS_TOPIC,
  CLOSE_COLLECTION_TOPIC,
  STUDENT_API_TOPIC,
  UPDATE_STUDENT_DOWNSTREAM_TOPIC,
  UPDATE_STUDENT_DOWNSTREAM_SAGA_TOPIC,
  UPDATE_STUDENT_STATUS_SAGA_TOPIC,
  SDC_EVENTS_TOPIC,
  PEN_SERVICES_API_TOPIC
}
