--In SDC Schema
CREATE INDEX sdc_coll_student_sdc_school_collection_student_status_code_idx ON api_student_data_collection.sdc_school_collection_student USING btree (sdc_school_collection_student_status_code);
CREATE INDEX sdc_coll_student_sdc_school_collection_id_idx ON api_student_data_collection.sdc_school_collection_student USING btree (sdc_school_collection_id);
CREATE INDEX sdc_school_collection_collection_id_idx ON api_student_data_collection.sdc_school_collection USING btree (collection_id);
CREATE INDEX sdc_school_collection_district_collection_id_idx ON api_student_data_collection.sdc_school_collection USING btree (sdc_district_collection_id);

