--In SDC Schema
drop index sdc_coll_student_sdc_school_collection_student_status_code_idx;
drop index sdc_coll_student_sdc_school_collection_id_idx;
drop index sdc_school_collection_collection_id_idx;
drop index sdc_school_collection_district_collection_id_idx;
