INSERT INTO COLLECTION_STATUS_CODE (COLLECTION_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                    EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                    UPDATE_USER, UPDATE_DATE)
VALUES ('DUPES_RESLV', 'Duplicates Resolved', 'All duplicates are resolved', '25', TO_DATE('20240715', 'YYYYMMDD'),
        TO_DATE('99991231', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',TO_DATE('20240715', 'YYYYMMDD'),
        'API_STUDENT_DATA_COLLECTION', TO_DATE('20240715', 'YYYYMMDD'));
