UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Home School Registration',
    DESCRIPTION = 'Home School Registration'
WHERE ENROLLED_GRADE_CODE = '00';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Grade 1',
    DESCRIPTION = 'Grade 1'
WHERE ENROLLED_GRADE_CODE = '01';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Grade 2',
    DESCRIPTION = 'Grade 2'
WHERE ENROLLED_GRADE_CODE = '02';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Grade 3',
    DESCRIPTION = 'Grade 3'
WHERE ENROLLED_GRADE_CODE = '03';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Grade 4',
    DESCRIPTION = 'Grade 4'
WHERE ENROLLED_GRADE_CODE = '04';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Grade 5',
    DESCRIPTION = 'Grade 5'
WHERE ENROLLED_GRADE_CODE = '05';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Grade 6',
    DESCRIPTION = 'Grade 6'
WHERE ENROLLED_GRADE_CODE = '06';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Grade 7',
    DESCRIPTION = 'Grade 7'
WHERE ENROLLED_GRADE_CODE = '07';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Grade 8',
    DESCRIPTION = 'Grade 8'
WHERE ENROLLED_GRADE_CODE = '08';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Grade 9',
    DESCRIPTION = 'Grade 9'
WHERE ENROLLED_GRADE_CODE = '09';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Grade 10',
    DESCRIPTION = 'Grade 10'
WHERE ENROLLED_GRADE_CODE = '10';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Grade 11',
    DESCRIPTION = 'Grade 11'
WHERE ENROLLED_GRADE_CODE = '11';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Grade 12',
    DESCRIPTION = 'Grade 12'
WHERE ENROLLED_GRADE_CODE = '12';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Kindergarten Full-Time',
    DESCRIPTION = 'Kindergarten Full-Time'
WHERE ENROLLED_GRADE_CODE = '19';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Grades 1-3',
    DESCRIPTION = 'Grades 1-3'
WHERE ENROLLED_GRADE_CODE = '29';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Elementary Special Ungraded',
    DESCRIPTION = 'Elementary Special Ungraded'
WHERE ENROLLED_GRADE_CODE = '79';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Secondary Special Ungraded',
    DESCRIPTION = 'Secondary Special Ungraded'
WHERE ENROLLED_GRADE_CODE = '89';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Elementary Ungraded',
    DESCRIPTION = 'Elementary Ungraded'
WHERE ENROLLED_GRADE_CODE = 'EU';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Graduated Adult',
    DESCRIPTION = 'Graduated Adult'
WHERE ENROLLED_GRADE_CODE = 'GA';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Home School Registration',
    DESCRIPTION = 'Home School Registration'
WHERE ENROLLED_GRADE_CODE = 'HS';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Kindergarten Full-Time',
    DESCRIPTION = 'Kindergarten Full-Time'
WHERE ENROLLED_GRADE_CODE = 'KF';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Kindergarten Half-Time',
    DESCRIPTION = 'Kindergarten Half-Time'
WHERE ENROLLED_GRADE_CODE = 'KH';

UPDATE ENROLLED_GRADE_CODE
SET LABEL = 'Secondary Ungraded',
    DESCRIPTION = 'Secondary Ungraded'
WHERE ENROLLED_GRADE_CODE = 'SU';
