ALTER TABLE COLLECTION ALTER COLUMN CLOSE_DATE DROP NOT NULL;

ALTER TABLE COLLECTION_TYPE_CODE DROP COLUMN OPEN_DATE;
ALTER TABLE COLLECTION_TYPE_CODE DROP COLUMN CLOSE_DATE;

UPDATE COLLECTION
SET CLOSE_DATE = null
WHERE COLLECTION_STATUS != 'COMPLETED';
