ALTER TABLE COLLECTION
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE COLLECTION
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE COLLECTION_CODE_CRITERIA
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE COLLECTION_CODE_CRITERIA
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE COLLECTION_EVENT
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE COLLECTION_EVENT
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SAGA
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SAGA
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SAGA_EVENT_STATES
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SAGA_EVENT_STATES
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SCHOOL_COLLECTION
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SCHOOL_COLLECTION
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SCHOOL_COLLECTION_HISTORY
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SCHOOL_COLLECTION_HISTORY
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_ENROLLED_PROGRAM
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_ENROLLED_PROGRAM
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_HISTORY
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_HISTORY
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_VALIDATION_ISSUE
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_VALIDATION_ISSUE
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_STUDENT_ELL
    ALTER COLUMN CREATE_USER TYPE VARCHAR(100);

ALTER TABLE SDC_STUDENT_ELL
    ALTER COLUMN UPDATE_USER TYPE VARCHAR(100);


