ALTER TABLE STUDENT_DATA_COLLECTION_SCHOOL
RENAME COLUMN COLLECTION_STATUS_TYPE_CODE TO STATUS_CODE;

ALTER TABLE STUDENT_DATA_COLLECTION_SCHOOL_STUDENT
    RENAME COLUMN STATUS_TYPE_CODE TO STATUS_CODE;
