INSERT INTO SCHOOL_FUNDING_CODE (SCHOOL_FUNDING_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                 EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                 UPDATE_USER, UPDATE_DATE)
VALUES ('16', 'Newcomer Refugee', 'Newcomer Refugee', '10',
        TO_DATE('19880930', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'),
        'API_STUDENT_DATA_COLLECTION', TO_DATE('23-02-08', 'YYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        TO_DATE('23-02-08', 'YYMMDD'));
