CREATE TABLE SDC_DISTRICT_COLLECTION_SUBMISSION_SIGNATURE
(
    SDC_DISTRICT_SUBMISSION_SIGNATURE_ID        UUID                                NOT NULL,
    SDC_DISTRICT_COLLECTION_ID                  UUID                                NOT NULL,
    DISTRICT_SIGNATORY_USER_ID                  VARCHAR(100)                        NOT NULL,
    CREATE_USER                                 VARCHAR(100)                        NOT NULL,
    CREATE_DATE                                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                                 VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SDC_DISTRICT_SUBMISSION_SIGNATURE_ID_PK PRIMARY KEY (SDC_DISTRICT_SUBMISSION_SIGNATURE_ID)
);

ALTER TABLE SDC_DISTRICT_COLLECTION_SUBMISSION_SIGNATURE
    ADD CONSTRAINT FK_SDC_DISTRICT_COLLECTION_ID FOREIGN KEY (SDC_DISTRICT_COLLECTION_ID)
        REFERENCES SDC_DISTRICT_COLLECTION (SDC_DISTRICT_COLLECTION_ID);

CREATE INDEX SDC_SUBMISSION_SIGN_SDC_DISTRICT_COLLECTION_ID_IDX ON SDC_DISTRICT_COLLECTION_SUBMISSION_SIGNATURE (SDC_DISTRICT_COLLECTION_ID);
