ALTER TABLE COLLECTION_TYPE_CODE
    ADD COLUMN SNAPSHOT_DATE TIMESTAMP;

UPDATE COLLECTION_TYPE_CODE
SET SNAPSHOT_DATE = '9999-09-29'
WHERE COLLECTION_TYPE_CODE = 'SEPTEMBER';

UPDATE COLLECTION_TYPE_CODE
SET SNAPSHOT_DATE = '9999-02-10'
WHERE COLLECTION_TYPE_CODE = 'FEBRUARY';

UPDATE COLLECTION_TYPE_CODE
SET SNAPSHOT_DATE = '9999-05-05'
WHERE COLLECTION_TYPE_CODE = 'MAY';

UPDATE COLLECTION_TYPE_CODE
SET SNAPSHOT_DATE = '9999-06-05'
WHERE COLLECTION_TYPE_CODE = 'JUNE';

UPDATE COLLECTION_TYPE_CODE
SET SNAPSHOT_DATE = '9999-07-07'
WHERE COLLECTION_TYPE_CODE = 'JULY';

ALTER TABLE COLLECTION_TYPE_CODE
    ALTER COLUMN SNAPSHOT_DATE SET NOT NULL;


ALTER TABLE COLLECTION
    ADD COLUMN SNAPSHOT_DATE TIMESTAMP;

ALTER TABLE COLLECTION
    ADD COLUMN SUBMISSION_DUE_DATE TIMESTAMP;

ALTER TABLE COLLECTION
    ADD COLUMN DUPLICATION_RESOLUTION_DUE_DATE TIMESTAMP;

ALTER TABLE COLLECTION
    ADD COLUMN SIGN_OFF_DUE_DATE TIMESTAMP;

UPDATE COLLECTION
SET SNAPSHOT_DATE =
    CASE
        WHEN COLLECTION_TYPE_CODE = 'SEPTEMBER' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-09-29', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'FEBRUARY' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-02-10', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'MAY' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-05-05', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'JULY' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-07-07', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'JUNE' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-06-05', 'YYYY-MM-DD')
        END;

UPDATE COLLECTION
SET SUBMISSION_DUE_DATE =
    CASE
        WHEN COLLECTION_TYPE_CODE = 'SEPTEMBER' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-09-29', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'FEBRUARY' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-02-10', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'MAY' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-05-05', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'JULY' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-07-07', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'JUNE' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-06-05', 'YYYY-MM-DD')
        END;

UPDATE COLLECTION
SET DUPLICATION_RESOLUTION_DUE_DATE =
    CASE
        WHEN COLLECTION_TYPE_CODE = 'SEPTEMBER' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-09-29', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'FEBRUARY' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-02-10', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'MAY' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-05-05', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'JULY' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-07-07', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'JUNE' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-06-05', 'YYYY-MM-DD')
        END;

UPDATE COLLECTION
SET SIGN_OFF_DUE_DATE =
    CASE
        WHEN COLLECTION_TYPE_CODE = 'SEPTEMBER' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-09-29', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'FEBRUARY' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-02-10', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'MAY' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-05-05', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'JULY' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-07-07', 'YYYY-MM-DD')
        WHEN COLLECTION_TYPE_CODE = 'JUNE' THEN TO_DATE(EXTRACT(YEAR FROM OPEN_DATE) || '-06-05', 'YYYY-MM-DD')
        END;