ALTER TABLE sdc_duplicate_student ALTER COLUMN sdc_district_collection_id DROP NOT NULL;

ALTER TABLE sdc_duplicate
    ADD COLUMN collection_id UUID NOT NULL,
ADD CONSTRAINT FK_COLLECTION_ID FOREIGN KEY (collection_id) REFERENCES COLLECTION (COLLECTION_ID);