INSERT INTO HOME_LANGUAGE_SPOKEN_CODE (HOME_LANGUAGE_SPOKEN_CODE, LABEL, DESCRIPTION,
                                       DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                       CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('367', 'NUER', 'NUER', '10', TO_DATE('20240701', 'YYYYMMDD'),
        TO_DATE('99991231', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        TO_DATE('25-03-26', 'YYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        TO_DATE('25-03-26', 'YYMMDD'));
INSERT INTO HOME_LANGUAGE_SPOKEN_CODE (HOME_LANGUAGE_SPOKEN_CODE, LABEL, DESCRIPTION,
                                       DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER,
                                       CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('368', 'ROHINGYA', 'ROHINGYA', '10', TO_DATE('20240701', 'YYYYMMDD'),
        TO_DATE('99991231', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        TO_DATE('25-03-26', 'YYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        TO_DATE('25-03-26', 'YYMMDD'));