
ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT
ADD COLUMN ASSIGNED_STUDENT_ID UUID;

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT
ADD COLUMN ASSIGNED_PEN VARCHAR(10);

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_HISTORY
ADD COLUMN ASSIGNED_STUDENT_ID UUID;

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_HISTORY
ADD COLUMN ASSIGNED_PEN VARCHAR(10);
