CREATE INDEX idx_student_collection_assigned_id_status
    ON SDC_SCHOOL_COLLECTION_STUDENT (
        SDC_SCHOOL_COLLECTION_ID,
        ASSIGNED_STUDENT_ID
    )
    WHERE SDC_SCHOOL_COLLECTION_STUDENT_STATUS_CODE <> 'DELETED'
      AND ASSIGNED_STUDENT_ID IS NOT NULL;


