ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_HISTORY
    ADD COLUMN UNDER_REVIEW_ASSIGNED_STUDENT_ID UUID;

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_HISTORY
    ADD COLUMN UNDER_REVIEW_ASSIGNED_PEN VARCHAR(10);

