UPDATE SDC_DISTRICT_COLLECTION_STATUS_CODE
SET SDC_DISTRICT_COLLECTION_STATUS_CODE='LOADED',
    LABEL='Loaded',
    DESCRIPTION='District has passed the file upload step.'
WHERE SDC_DISTRICT_COLLECTION_STATUS_CODE='MONITORING';