ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT
ADD COLUMN ORIGINAL_DEMOG_HASH VARCHAR(4000) NOT NULL DEFAULT 'N/A';

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT
ADD COLUMN CURRENT_DEMOG_HASH VARCHAR(4000) NOT NULL DEFAULT 'N/A';

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_HISTORY
ADD COLUMN ORIGINAL_DEMOG_HASH VARCHAR(4000) NOT NULL DEFAULT 'N/A';

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_HISTORY
ADD COLUMN CURRENT_DEMOG_HASH VARCHAR(4000) NOT NULL DEFAULT 'N/A';
