CREATE TABLE SDC_STUDENT_ELL
(
    SDC_STUDENT_ELL_ID   UUID                           NOT NULL,
    STUDENT_ID      UUID                                NOT NULL,
    YEARS_IN_ELL    NUMERIC                             NOT NULL,
    CREATE_USER     VARCHAR(32)                         NOT NULL,
    CREATE_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER     VARCHAR(32)                         NOT NULL,
    UPDATE_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SDC_STUDENT_ELL_ID_PK PRIMARY KEY (SDC_STUDENT_ELL_ID)
);
