CREATE TABLE COLLECTION_STATUS_CODE
(
    COLLECTION_STATUS_CODE VARCHAR(10)                         NOT NULL,
    LABEL                       VARCHAR(30)                         NOT NULL,
    DESCRIPTION                 VARCHAR(255)                        NOT NULL,
    DISPLAY_ORDER               NUMERIC   DEFAULT 1                 NOT NULL,
    EFFECTIVE_DATE              TIMESTAMP                           NOT NULL,
    EXPIRY_DATE                 TIMESTAMP                           NOT NULL,
    CREATE_USER                 VARCHAR(32)                         NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(32)                         NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT COLLECTION_STATUS_CODE_PK PRIMARY KEY (COLLECTION_STATUS_CODE)
);

INSERT INTO COLLECTION_STATUS_CODE (COLLECTION_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                  EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                  UPDATE_USER, UPDATE_DATE)
VALUES ('INPROGRESS', 'In Progress', 'Collection is in progress', '10', TO_DATE('20230210', 'YYYYMMDD'),
        TO_DATE('99991231', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        TO_DATE('20230210', 'YYYYMMDD'),
        'API_STUDENT_DATA_COLLECTION', TO_DATE('20230210', 'YYYYMMDD'));

INSERT INTO COLLECTION_STATUS_CODE (COLLECTION_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                    EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                    UPDATE_USER, UPDATE_DATE)
VALUES ('PROVDUPES', 'Provincial Duplicates', 'Collection is resolving provincial duplicates', '20', TO_DATE('20230210', 'YYYYMMDD'),
        TO_DATE('99991231', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        TO_DATE('20230210', 'YYYYMMDD'),
        'API_STUDENT_DATA_COLLECTION', TO_DATE('20230210', 'YYYYMMDD'));

INSERT INTO COLLECTION_STATUS_CODE (COLLECTION_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                    EXPIRY_DATE, CREATE_USER, CREATE_DATE,
                                    UPDATE_USER, UPDATE_DATE)
VALUES ('COMPLETED', 'Completed', 'Collection is completed', '30', TO_DATE('20230210', 'YYYYMMDD'),
        TO_DATE('99991231', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        TO_DATE('20230210', 'YYYYMMDD'),
        'API_STUDENT_DATA_COLLECTION', TO_DATE('20230210', 'YYYYMMDD'));

ALTER TABLE COLLECTION
    ADD COLUMN COLLECTION_STATUS_CODE VARCHAR(10) NOT NULL DEFAULT 'COMPLETED';

ALTER TABLE COLLECTION
    ALTER COLUMN COLLECTION_STATUS_CODE DROP DEFAULT;
