ALTER TABLE SDC_SCHOOL_COLLECTION
    DROP CONSTRAINT UNQ_SDC_SCHOOL_COLLECTION_ID_SCHOOLID;

ALTER TABLE SDC_SCHOOL_COLLECTION
    ADD CONSTRAINT FK_SDC_DISTRICT_COLLECTION_SDC_DISTRICT_COLLECTION_ID FOREIGN KEY (SDC_DISTRICT_COLLECTION_ID)
    REFERENCES SDC_DISTRICT_COLLECTION (SDC_DISTRICT_COLLECTION_ID);

ALTER TABLE SDC_SCHOOL_COLLECTION
    ADD CONSTRAINT UNQ_SDC_SCHOOL_COLLECTION_ID_SCHOOL_ID_SDC_DISTRICT_COLLECTION_ID UNIQUE (COLLECTION_ID, SCHOOL_ID, SDC_DISTRICT_COLLECTION_ID);

INSERT INTO SDC_DISTRICT_COLLECTION_STATUS_CODE (SDC_DISTRICT_COLLECTION_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                                 EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('REVIEWED', 'Reviewed', 'District has reviewed all the students', '30',
        TO_DATE('20230210', 'YYYYMMDD'),
        TO_DATE('99991231', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        CURRENT_TIMESTAMP,
        'API_STUDENT_DATA_COLLECTION', CURRENT_TIMESTAMP);