ALTER TABLE SDC_SCHOOL_COLLECTION
    ADD COLUMN SDC_DISTRICT_COLLECTION_ID UUID,
    ADD CONSTRAINT FK_SDC_SCHOOL_SDC_DISTRICT_COLLECTION_ID FOREIGN KEY (SDC_DISTRICT_COLLECTION_ID)
    REFERENCES SDC_DISTRICT_COLLECTION (SDC_DISTRICT_COLLECTION);

