UPDATE HOME_LANGUAGE_SPOKEN_CODE
SET LABEL = 'Nuer', DESCRIPTION = 'Nuer'
WHERE HOME_LANGUAGE_SPOKEN_CODE = '367';

UPDATE HOME_LANGUAGE_SPOKEN_CODE
SET LABEL = 'Rohingya', DESCRIPTION = 'Rohingya'
WHERE HOME_LANGUAGE_SPOKEN_CODE = '368';

INSERT INTO HOME_LANGUAGE_SPOKEN_CODE
(HOME_LANGUAGE_SPOKEN_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES
    ('363', 'Burmese', 'Burmese', '10', TO_DATE('20240701', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'),
     'API_STUDENT_DATA_COLLECTION', TO_DATE('25-03-27', 'YYMMDD'), 'API_STUDENT_DATA_COLLECTION', TO_DATE('25-03-27', 'YYMMDD'));

INSERT INTO HOME_LANGUAGE_SPOKEN_CODE
(HOME_LANGUAGE_SPOKEN_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES
    ('364', 'Amharic', 'Amharic', '10', TO_DATE('20240701', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'),
     'API_STUDENT_DATA_COLLECTION', TO_DATE('25-03-27', 'YYMMDD'), 'API_STUDENT_DATA_COLLECTION', TO_DATE('25-03-27', 'YYMMDD'));

INSERT INTO HOME_LANGUAGE_SPOKEN_CODE
(HOME_LANGUAGE_SPOKEN_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES
    ('365', 'Montenegrin', 'Montenegrin', '10', TO_DATE('20240701', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'),
     'API_STUDENT_DATA_COLLECTION', TO_DATE('25-03-27', 'YYMMDD'), 'API_STUDENT_DATA_COLLECTION', TO_DATE('25-03-27', 'YYMMDD'));

INSERT INTO HOME_LANGUAGE_SPOKEN_CODE
(HOME_LANGUAGE_SPOKEN_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES
    ('366', 'Myanmar chin', 'Myanmar chin', '10', TO_DATE('20240701', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'),
     'API_STUDENT_DATA_COLLECTION', TO_DATE('25-03-27', 'YYMMDD'), 'API_STUDENT_DATA_COLLECTION', TO_DATE('25-03-27', 'YYMMDD'));