CREATE TABLE SDC_DISTRICT_COLLECTION_STATUS_CODE
(
    SDC_DISTRICT_COLLECTION_STATUS_CODE VARCHAR(10)                 NOT NULL,
    LABEL                       VARCHAR(30)                         NOT NULL,
    DESCRIPTION                 VARCHAR(255)                        NOT NULL,
    DISPLAY_ORDER               NUMERIC   DEFAULT 1                 NOT NULL,
    EFFECTIVE_DATE              TIMESTAMP                           NOT NULL,
    EXPIRY_DATE                 TIMESTAMP                           NOT NULL,
    CREATE_USER                 VARCHAR(100)                        NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SDC_DISTRICT_COLLECTION_STATUS_CODE_PK PRIMARY KEY (SDC_DISTRICT_COLLECTION_STATUS_CODE)
);

INSERT INTO SDC_DISTRICT_COLLECTION_STATUS_CODE (SDC_DISTRICT_COLLECTION_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                                        EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('NEW', 'New', 'Collection record has been created.', '10',
        TO_DATE('20230210', 'YYYYMMDD'),
        TO_DATE('99991231', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        CURRENT_TIMESTAMP,
        'API_STUDENT_DATA_COLLECTION', CURRENT_TIMESTAMP);

INSERT INTO SDC_DISTRICT_COLLECTION_STATUS_CODE (SDC_DISTRICT_COLLECTION_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                                 EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('MONITORING', 'Monitoring Uploads', 'Monitoring schools upload status.', '20',
        TO_DATE('20230210', 'YYYYMMDD'),
        TO_DATE('99991231', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        CURRENT_TIMESTAMP,
        'API_STUDENT_DATA_COLLECTION', CURRENT_TIMESTAMP);

INSERT INTO SDC_DISTRICT_COLLECTION_STATUS_CODE (SDC_DISTRICT_COLLECTION_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                                 EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('COMPLETED', 'Completed', 'Collection signed off by the Ministry.', '80',
        TO_DATE('20230210', 'YYYYMMDD'),
        TO_DATE('99991231', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        CURRENT_TIMESTAMP,
        'API_STUDENT_DATA_COLLECTION', CURRENT_TIMESTAMP);

CREATE TABLE SDC_DISTRICT_COLLECTION
(
    SDC_DISTRICT_COLLECTION_ID          UUID                                NOT NULL,
    COLLECTION_ID                       UUID                                NOT NULL,
    DISTRICT_ID                         UUID                                NOT NULL,
    SDC_DISTRICT_COLLECTION_STATUS_CODE VARCHAR(10)                         NOT NULL,
    CREATE_USER                         VARCHAR(100)                        NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(100)                        NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SDC_DISTRICT_COLLECTION_ID_PK PRIMARY KEY (SDC_DISTRICT_COLLECTION_ID),
    CONSTRAINT UNQ_SDC_DISTRICT_COLLECTION_ID_DISTRICT_ID UNIQUE (COLLECTION_ID, DISTRICT_ID)
);

ALTER TABLE SDC_DISTRICT_COLLECTION
    ADD CONSTRAINT FK_SDC_DISTRICT_SDC_DISTRICT_COLLECTION_STATUS_CODE FOREIGN KEY (SDC_DISTRICT_COLLECTION_STATUS_CODE)
        REFERENCES SDC_DISTRICT_COLLECTION_STATUS_CODE (SDC_DISTRICT_COLLECTION_STATUS_CODE);

CREATE INDEX SDC_DISTRICT_ID_IDX ON SDC_SCHOOL_COLLECTION (DISTRICT_ID);