ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_HISTORY
ADD COLUMN PEN_MATCH_RESULT VARCHAR(8);

INSERT INTO SDC_SCHOOL_COLLECTION_STUDENT_STATUS_CODE (SDC_SCHOOL_COLLECTION_STUDENT_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                                       EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('HASISSUES', 'Has Issues', 'Student record has issues of type ERROR, WARNING or FUNDING WARNING.', '10',
        TO_DATE('20230210', 'YYYYMMDD'),
        TO_DATE('99991231', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        TO_DATE('20230210', 'YYYYMMDD'),
        'API_STUDENT_DATA_COLLECTION', TO_DATE('20230210', 'YYYYMMDD'));

DELETE FROM SDC_SCHOOL_COLLECTION_STUDENT_STATUS_CODE
WHERE SDC_SCHOOL_COLLECTION_STUDENT_STATUS_CODE in ('WARNING', 'ERROR');
