INSERT INTO SDC_SCHOOL_COLLECTION_STUDENT_STATUS_CODE (SDC_SCHOOL_COLLECTION_STUDENT_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                                       EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('DEMOG_UPD', 'Demographic Update', 'Update student record in downstream system.', '10',
        TO_DATE('20240723', 'YYYYMMDD'),
        TO_DATE('99991231', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        TO_DATE('20240723', 'YYYYMMDD'),
        'API_STUDENT_DATA_COLLECTION', TO_DATE('20240723', 'YYYYMMDD'));

INSERT INTO SDC_SCHOOL_COLLECTION_STUDENT_STATUS_CODE (SDC_SCHOOL_COLLECTION_STUDENT_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                                       EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('COMPLETED', 'Completed', '1701 completed for student.', '10',
        TO_DATE('20240723', 'YYYYMMDD'),
        TO_DATE('99991231', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        TO_DATE('20240723', 'YYYYMMDD'),
        'API_STUDENT_DATA_COLLECTION', TO_DATE('20240723', 'YYYYMMDD'));
