CREATE TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP
(
    SCHOOL_FUNDING_GROUP_ID             UUID NOT NULL,
    SCHOOL_ID                           UUID NOT NULL,
    SCHOOL_GRADE_CODE                   VARCHAR(10) NOT NULL,
    SCHOOL_FUNDING_GROUP_CODE           VARCHAR(10) NOT NULL,
    CREATE_USER                         VARCHAR(32)         NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(32)         NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SCHOOL_FUNDING_GROUP_ID_PK PRIMARY KEY (SCHOOL_FUNDING_GROUP_ID)
);

CREATE TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT
(
    SCHOOL_FUNDING_GROUP_SNAPSHOT_ID    UUID NOT NULL,
    COLLECTION_ID                       UUID NOT NULL,
    SCHOOL_ID                           UUID NOT NULL,
    SCHOOL_GRADE_CODE                   VARCHAR(10) NOT NULL,
    SCHOOL_FUNDING_GROUP_CODE           VARCHAR(10) NOT NULL,
    CREATE_USER                         VARCHAR(32)         NOT NULL,
    CREATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                         VARCHAR(32)         NOT NULL,
    UPDATE_DATE                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SCHOOL_FUNDING_GROUP_SNAPSHOT_ID_PK PRIMARY KEY (SCHOOL_FUNDING_GROUP_SNAPSHOT_ID)
);

CREATE TABLE SCHOOL_GRADE_CODE
(
    SCHOOL_GRADE_CODE           VARCHAR(10)                         NOT NULL,
    LABEL                       VARCHAR(30)                         NOT NULL,
    DESCRIPTION                 VARCHAR(255)                        NOT NULL,
    LEGACY_CODE                 VARCHAR(10),
    DISPLAY_ORDER               NUMERIC   DEFAULT 1                 NOT NULL,
    EFFECTIVE_DATE              TIMESTAMP                           NOT NULL,
    EXPIRY_DATE                 TIMESTAMP                           NOT NULL,
    CREATE_USER                 VARCHAR(32)                         NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(32)                         NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SCHOOL_GRADE_CODE_PK PRIMARY KEY (SCHOOL_GRADE_CODE)
);

CREATE TABLE SCHOOL_FUNDING_GROUP_CODE
(
    SCHOOL_FUNDING_GROUP_CODE           VARCHAR(10)                         NOT NULL,
    LABEL                       VARCHAR(30)                         NOT NULL,
    DESCRIPTION                 VARCHAR(255)                        NOT NULL,
    LEGACY_CODE                 VARCHAR(10),
    DISPLAY_ORDER               NUMERIC   DEFAULT 1                 NOT NULL,
    EFFECTIVE_DATE              TIMESTAMP                           NOT NULL,
    EXPIRY_DATE                 TIMESTAMP                           NOT NULL,
    CREATE_USER                 VARCHAR(32)                         NOT NULL,
    CREATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                 VARCHAR(32)                         NOT NULL,
    UPDATE_DATE                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SCHOOL_FUNDING_GROUP_CODE_PK PRIMARY KEY (SCHOOL_FUNDING_GROUP_CODE)
);

ALTER TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT
    ADD CONSTRAINT FK_SCHOOL_FUNDING_COLLECTION_ID FOREIGN KEY (COLLECTION_ID)
        REFERENCES COLLECTION (COLLECTION_ID);

ALTER TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP
    ADD CONSTRAINT FK_SCHOOL_FUNDING_FUNDING_CODE FOREIGN KEY (SCHOOL_FUNDING_GROUP_CODE)
        REFERENCES SCHOOL_FUNDING_GROUP_CODE (SCHOOL_FUNDING_GROUP_CODE);

ALTER TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT
    ADD CONSTRAINT FK_SCHOOL_FUNDING_SNAP_FUNDING_CODE FOREIGN KEY (SCHOOL_FUNDING_GROUP_CODE)
        REFERENCES SCHOOL_FUNDING_GROUP_CODE (SCHOOL_FUNDING_GROUP_CODE);

ALTER TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP
    ADD CONSTRAINT FK_SCHOOL_FUNDING_GRADE_CODE FOREIGN KEY (SCHOOL_GRADE_CODE)
        REFERENCES SCHOOL_GRADE_CODE (SCHOOL_GRADE_CODE);

ALTER TABLE INDEPENDENT_SCHOOL_FUNDING_GROUP_SNAPSHOT
    ADD CONSTRAINT FK_SCHOOL_FUNDING_SNAP_GRADE_CODE FOREIGN KEY (SCHOOL_GRADE_CODE)
        REFERENCES SCHOOL_GRADE_CODE (SCHOOL_GRADE_CODE);
