CREATE TABLE SDC_SCHOOL_COLLECTION_STUDENT_ENROLLED_PROGRAM
(
    SDC_SCHOOL_COLLECTION_STUDENT_ENROLLED_PROGRAM_ID   UUID            NOT NULL,
    SDC_SCHOOL_COLLECTION_STUDENT_ID                    VARCHAR(10)     NOT NULL,
    ENROLLED_PROGRAM_CODE                               VARCHAR(2)      NOT NULL,
    CREATE_USER                                         VARCHAR(32)     NOT NULL,
    CREATE_DATE                                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                                         VARCHAR(32)     NOT NULL,
    UPDATE_DATE                                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT SDC_SCHOOL_COLLECTION_STUDENT_ENROLLED_PROGRAM_ID_PK PRIMARY KEY (SDC_SCHOOL_COLLECTION_STUDENT_ENROLLED_PROGRAM_ID)
);

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_ENROLLED_PROGRAM
    ADD CONSTRAINT FK_SDC_SCHOOL_STUDENT_EP_SDC_SCHOOL_COLLECTION_STUD_ID FOREIGN KEY (SDC_SCHOOL_COLLECTION_STUDENT_ID)
        REFERENCES SDC_SCHOOL_COLLECTION_STUDENT (SDC_SCHOOL_COLLECTION_STUDENT_ID);


