INSERT INTO COLLECTION_TYPE_CODE (COLLECTION_TYPE_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                             EXPIRY_DATE, OPEN_DATE, CLOSE_DATE, CREATE_USER, CREATE_DATE,
                             UPDATE_USER, UPDATE_DATE)
VALUES ('JUNE', 'June', 'June Collection', '10', TO_DATE('19950601', 'YYYYMMDD'),
        TO_DATE('19950630', 'YYYYMMDD'), TO_DATE('19950601', 'YYYYMMDD'),
        TO_DATE('19950630', 'YYYYMMDD'), 'API_STUDENT_DATA_COLLECTION',
        TO_DATE('20230210', 'YYYYMMDD'),
        'API_STUDENT_DATA_COLLECTION', TO_DATE('20230210', 'YYYYMMDD'));
