ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT
ADD COLUMN IS_ADULT BOOLEAN;

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT
ADD COLUMN IS_SCHOOL_AGED BOOLEAN;

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_HISTORY
ADD COLUMN IS_ADULT BOOLEAN;

ALTER TABLE SDC_SCHOOL_COLLECTION_STUDENT_HISTORY
ADD COLUMN IS_SCHOOL_AGED BOOLEAN;