package ca.bc.gov.educ.studentdatacollection.api.constants.v1;

import lombok.Getter;

import java.util.Arrays;
import java.util.Optional;

/**
 * The enum Event outcome.
 */
public enum DistrictReportTypeCode {

  DIS_GRADE_ENROLLMENT_HEADCOUNT("DIS_GRADE_ENROLLMENT_HEADCOUNT"),
  DIS_GRADE_ENROLLMENT_HEADCOUNT_PER_SCHOOL("DIS_GRADE_ENROLLMENT_HEADCOUNT_PER_SCHOOL"),
  DIS_ELL_HEADCOUNT("DIS_ELL_HEADCOUNT"),
  DIS_ELL_HEADCOUNT_PER_SCHOOL("DIS_ELL_HEADCOUNT_PER_SCHOOL"),
  DIS_REFUGEE_HEADCOUNT_PER_SCHOOL("DIS_REFUGEE_HEADCOUNT_PER_SCHOOL"),
  DIS_SPECIAL_EDUCATION_HEADCOUNT("DIS_SPECIAL_EDUCATION_HEADCOUNT"),
  DIS_SPECIAL_EDUCATION_HEADCOUNT_PER_SCHOOL("DIS_SPECIAL_EDUCATION_HEADCOUNT_PER_SCHOOL"),
  DIS_SPECIAL_EDUCATION_HEADCOUNT_CATEGORY_PER_SCHOOL("DIS_SPECIAL_EDUCATION_HEADCOUNT_CATEGORY_PER_SCHOOL"),
  DIS_INDIGENOUS_HEADCOUNT("DIS_INDIGENOUS_HEADCOUNT"),
  DIS_INDIGENOUS_HEADCOUNT_PER_SCHOOL("DIS_INDIGENOUS_HEADCOUNT_PER_SCHOOL"),
  DIS_FRENCH_HEADCOUNT("DIS_FRENCH_HEADCOUNT"),
  DIS_FRENCH_HEADCOUNT_PER_SCHOOL("DIS_FRENCH_HEADCOUNT_PER_SCHOOL"),
  DIS_CAREER_HEADCOUNT("DIS_CAREER_HEADCOUNT"),
  DIS_CAREER_HEADCOUNT_PER_SCHOOL("DIS_CAREER_HEADCOUNT_PER_SCHOOL"),
  ALL_STUDENT_DIS_CSV("ALL_STUDENT_DIS_CSV"),
  ALL_STUDENT_ERRORS_WARNS_DIS_CSV("ALL_STUDENT_ERRORS_WARNS_DIS_CSV"),
  ALL_STUDENT_FRENCH_DIS_CSV("ALL_STUDENT_FRENCH_DIS_CSV"),
  ALL_STUDENT_CAREER_DIS_CSV("ALL_STUDENT_CAREER_DIS_CSV"),
  ALL_STUDENT_INDIGENOUS_DIS_CSV("ALL_STUDENT_INDIGENOUS_DIS_CSV"),
  DIS_ZERO_FTE_SUMMARY("DIS_ZERO_FTE_SUMMARY"),
  DIS_BAND_RESIDENCE_HEADCOUNT("DIS_BAND_RESIDENCE_HEADCOUNT"),
  DIS_BAND_RESIDENCE_HEADCOUNT_PER_SCHOOL("DIS_BAND_RESIDENCE_HEADCOUNT_PER_SCHOOL"),
  ;

  @Getter
  private final String code;
  DistrictReportTypeCode(String code) {
    this.code = code;
  }

  public static Optional<DistrictReportTypeCode> findByValue(String value) {
    return Arrays.stream(values()).filter(e -> Arrays.asList(e.code).contains(value)).findFirst();
  }

}
