package ca.bc.gov.educ.studentdatacollection.api.constants.v1;

import lombok.Getter;

import java.util.Arrays;
import java.util.Optional;

public enum ValidationRulesDependencyMatrix {
    ENTRY1("V15", new String[]{"LEGALLASTNAMEBLANK"}),
    ENTRY2("V13", new String[]{"LEGALFIRSTNAMECHARFIX"}),
    ENTRY3("V14", new String[]{"LEGALMIDDLENAMECHARFIX"}),
    ENTRY4("V16", new String[]{"USUALFIRSTNAMECHARFIX"}),
    ENTRY5("V18", new String[]{"USUALLASTNAMECHARFIX"}),
    ENTRY6("V21", new String[]{"PENCHECKDIGITERR"}),
    ENTRY7("V64", new String[]{"MISSINGPOSTALCODE"}),
    ENTRY8("V17", new String[]{"USUALMIDDLENAMECHARFIX"}),
    ENTRY9("V40", new String[]{"BANDCODEINVALID", "FUNDINGCODEINVALID"}),
    ENTRY10("V39", new String[]{"NATIVEINDINVALID", "ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID"}),
    ENTRY11("V52", new String[]{"FUNDINGCODEINVALID", "ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID", "CAREERCODEINVALID"}),
    ENTRY12("V30", new String[]{"ENROLLEDCODEPARSEERR"}),
    ENTRY13("V59", new String[]{"CAREERCODEINVALID", "ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID"}),
    ENTRY14("V73", new String[]{"INVALIDGRADECODE"}),
    ENTRY15("V44", new String[]{"INVALIDGRADECODE"}),
    ENTRY16("V72", new String[]{"INVALIDGRADECODE"}),
    ENTRY17("V37", new String[]{"DOBINVALIDFORMAT"}),
    ENTRY18("V53", new String[]{"DOBINVALIDFORMAT"}),
    ENTRY19("V54", new String[]{"DOBINVALIDFORMAT"}),
    ENTRY20("V36", new String[]{"DOBINVALIDFORMAT"}),
    ENTRY21("V49", new String[]{"DOBINVALIDFORMAT"}),
    ENTRY22("V45", new String[]{"DOBINVALIDFORMAT", "INVALIDGRADECODE"}),
    ENTRY23("V48", new String[]{"DOBINVALIDFORMAT", "INVALIDGRADECODE"}),
    ENTRY24("V57", new String[]{"DOBINVALIDFORMAT", "INVALIDGRADECODE"}),
    ENTRY25("V70", new String[]{"DOBINVALIDFORMAT", "INVALIDGRADECODE"}),
    ENTRY26("V43", new String[]{"DOBINVALIDFORMAT", "INVALIDGRADECODE"}),
    ENTRY27("V33", new String[]{"NOOFCOURSESINVALID", "DOBINVALIDFORMAT", "INVALIDGRADECODE"}),
    ENTRY28("V46", new String[]{"NOOFCOURSESINVALID", "DOBINVALIDFORMAT", "INVALIDGRADECODE"}),
    ENTRY29("V47", new String[]{"NOOFCOURSESINVALID", "DOBINVALIDFORMAT", "INVALIDGRADECODE"}),
    ENTRY30("V34", new String[]{"NOOFCOURSESINVALID", "DOBINVALIDFORMAT", "INVALIDGRADECODE"}),
    ENTRY31("V42", new String[]{"NOOFCOURSESINVALID"}),
    ENTRY32("V55", new String[]{"SPEDERR"}),
    ENTRY33("V65", new String[]{"NOOFCOURSESINVALID", "INVALIDGRADECODE", "SUPPORTBLOCKSINVALID"}),
    ENTRY34("V68", new String[]{"DOBINVALIDFORMAT", "SUPPORTBLOCKSINVALID", "INVALIDGRADECODE"}),
    ENTRY35("V69", new String[]{"DOBINVALIDFORMAT", "SUPPORTBLOCKSINVALID", "INVALIDGRADECODE"}),
    ENTRY36("V66", new String[]{"SUPPORTBLOCKSINVALID"}),
    ENTRY37("V71", new String[]{"SUPPORTBLOCKSINVALID"}),
    ENTRY38("V50", new String[]{"FUNDINGCODEINVALID", "ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID"}),
    ENTRY39("V51", new String[]{"FUNDINGCODEINVALID", "ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID"}),
    ENTRY40("V31", new String[]{"ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID"}),
    ENTRY41("V19", new String[]{"ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID"}),
    ENTRY42("V56", new String[]{"ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID", "CAREERCODEINVALID"}),
    ENTRY43("V61", new String[]{"ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID", "INVALIDGRADECODE", "CAREERCODECOUNTERR", "CAREERCODEINVALID"}),
    ENTRY44("V58", new String[]{"ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID", "CAREERCODECOUNTERR", "CAREERCODEINVALID"}),
    ENTRY45("V24", new String[]{"ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID", "CAREERCODEINVALID", "INVALIDGRADECODE"}),
    ENTRY46("V22", new String[]{"ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID", "INVALIDGRADECODE"}),
    ENTRY47("V23", new String[]{"ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID", "INVALIDGRADECODE"}),
    ENTRY48("V38", new String[]{"ENROLLEDCODEPARSEERR", "ENROLLEDCODEINVALID", "INVALIDGRADECODE"}),
    ENTRY49("V25", new String[]{"INVALIDGRADECODE", "SPEDERR"}),
    ENTRY50("V09", new String[]{"LEGALLASTNAMECHARFIX"}),
;
    @Getter
    private final String ruleID;
    @Getter
    private final String[] baseRuleErrorCode;
    ValidationRulesDependencyMatrix(String ruleID, String[] baseRuleErrorCode) {
        this.ruleID = ruleID;
        this.baseRuleErrorCode = baseRuleErrorCode;
    }

    public static Optional<ValidationRulesDependencyMatrix> findByValue(String ruleID) {
        return Arrays.stream(values()).filter(code -> code.ruleID.equalsIgnoreCase(ruleID)).findFirst();
    }
}
