package ca.bc.gov.educ.studentdatacollection.api.constants.v1.ministryreports;

import lombok.Getter;

@Getter
public enum EnrolmentAndFteHeader {

    DISTRICT_NUMBER("District Number"),
    SCHOOL_NUMBER("School Number"),
    SCHOOL_NAME("School Name"),
    FACILITY_TYPE("Facility Type"),
    KIND_HT_COUNT("Headcount Kind(H/T) Total"),
    GRADE_01_COUNT("Headcount Grade 1 Total"),
    GRADE_02_COUNT("Headcount Grade 2 Total"),
    GRADE_03_COUNT("Headcount Grade 3 Total"),
    GRADE_04_COUNT("Headcount Grade 4 Total"),
    GRADE_05_COUNT("Headcount Grade 5 Total"),
    GRADE_06_COUNT("Headcount Grade 6 Total"),
    GRADE_07_COUNT("Headcount Grade 7 Total"),
    GRADE_08_COUNT("Headcount Grade 8 Total"),
    GRADE_09_COUNT("Headcount Grade 9 Total"),
    GRADE_10_COUNT("Headcount Grade 10 Total"),
    GRADE_11_COUNT("Headcount Grade 11 Total"),
    GRADE_12_COUNT("Headcount Grade 12 Total"),
    GRADE_EU_COUNT("Headcount Grade EU Total"),
    GRADE_SU_COUNT("Headcount Grade SU Total"),
    GRADE_HS_COUNT("Headcount Homeschool "),
    GRAD_ADULT_COUNT("Headcount Grad Adult Total"),
    NON_GRAD_ADULT_COUNT("Headcount Non-Grad Adult Total"),

    KIND_HT_FTE_TOTAL("Funded FTE Kind(H/T) Total"),
    GRADE_ONE_FTE_TOTAL("Funded FTE Grade 1 Total"),
    GRADE_TWO_FTE_TOTAL("Funded FTE Grade 2 Total"),
    GRADE_THREE_FTE_TOTAL("Funded FTE Grade 3 Total"),
    GRADE_FOUR_FTE_TOTAL("Funded FTE Grade 4 Total"),
    GRADE_FIVE_FTE_TOTAL("Funded FTE Grade 5 Total"),
    GRADE_SIX_FTE_TOTAL("Funded FTE Grade 6 Total"),
    GRADE_SEVEN_FTE_TOTAL("Funded FTE Grade 7 Total"),
    GRADE_EIGHT_FTE_TOTAL("Funded FTE Grade 8 Total"),
    GRADE_NINE_FTE_TOTAL("Funded FTE Grade 9 Total"),
    GRADE_TEN_FTE_TOTAL("Funded FTE Grade 10 Total"),
    GRADE_ELEVEN_FTE_TOTAL("Funded FTE Grade 11 Total"),
    GRADE_TWELVE_FTE_TOTAL("Funded FTE Grade 12 Total"),
    EU_FTE_TOTAL("Funded FTE EU Total"),
    SU_FTE_TOTAL("Funded FTE SU Total"),

    KIND_HT_IE_LEVEL_ONE_COUNT("Headcount Kind(H/T) IE Level 1"),
    KIND_HT_IE_LEVEL_TWO_COUNT("Headcount Kind(H/T) IE Level 2"),
    KIND_HT_IE_LEVEL_THREE_COUNT("Headcount Kind(H/T) IE Level 3"),
    KIND_HT_ELL_COUNT("Headcount Kind(H/T) ELL"),
    KIND_HT_INDIGENOUS_COUNT("Headcount Kind(H/T) Indigenous"),
    KIND_HT_CORE_FRENCH_COUNT("Headcount Kind(H/T) Core French"),
    KIND_HT_EARLY_FRENCH_COUNT("Headcount Kind(H/T) Early French Immersion"),

    GRADE_01_IE_LEVEL_ONE_COUNT("Headcount Grade 1 IE Level 1"),
    GRADE_01_IE_LEVEL_TWO_COUNT("Headcount Grade 1 IE Level 2"),
    GRADE_01_IE_LEVEL_THREE_COUNT("Headcount Grade 1 IE Level 3"),
    GRADE_01_ELL_COUNT("Headcount Grade 1 ELL"),
    GRADE_01_INDIGENOUS_COUNT("Headcount Grade 1 Indigenous"),
    GRADE_01_CORE_FRENCH_COUNT("Headcount Grade 1 Core French"),
    GRADE_01_EARLY_FRENCH_COUNT("Headcount Grade 1 Early French Immersion"),

    GRADE_02_IE_LEVEL_ONE_COUNT("Headcount Grade 2 IE Level 1"),
    GRADE_02_IE_LEVEL_TWO_COUNT("Headcount Grade 2 IE Level 2"),
    GRADE_02_IE_LEVEL_THREE_COUNT("Headcount Grade 2 IE Level 3"),
    GRADE_02_ELL_COUNT("Headcount Grade 2 ELL"),
    GRADE_02_INDIGENOUS_COUNT("Headcount Grade 2 Indigenous"),
    GRADE_02_CORE_FRENCH_COUNT("Headcount Grade 2 Core French"),
    GRADE_02_EARLY_FRENCH_COUNT("Headcount Grade 2 Early French Immersion"),

    GRADE_03_IE_LEVEL_ONE_COUNT("Headcount Grade 3 IE Level 1"),
    GRADE_03_IE_LEVEL_TWO_COUNT("Headcount Grade 3 IE Level 2"),
    GRADE_03_IE_LEVEL_THREE_COUNT("Headcount Grade 3 IE Level 3"),
    GRADE_03_ELL_COUNT("Headcount Grade 3 ELL"),
    GRADE_03_INDIGENOUS_COUNT("Headcount Grade 3 Indigenous"),
    GRADE_03_CORE_FRENCH_COUNT("Headcount Grade 3 Core French"),
    GRADE_03_EARLY_FRENCH_COUNT("Headcount Grade 3 Early French Immersion"),

    GRADE_04_IE_LEVEL_ONE_COUNT("Headcount Grade 4 IE Level 1"),
    GRADE_04_IE_LEVEL_TWO_COUNT("Headcount Grade 4 IE Level 2"),
    GRADE_04_IE_LEVEL_THREE_COUNT("Headcount Grade 4 IE Level 3"),
    GRADE_04_ELL_COUNT("Headcount Grade 4 ELL"),
    GRADE_04_INDIGENOUS_COUNT("Headcount Grade 4 Indigenous"),
    GRADE_04_CORE_FRENCH_COUNT("Headcount Grade 4 Core French"),
    GRADE_04_EARLY_FRENCH_COUNT("Headcount Grade 4 Early French Immersion"),

    GRADE_05_IE_LEVEL_ONE_COUNT("Headcount Grade 5 IE Level 1"),
    GRADE_05_IE_LEVEL_TWO_COUNT("Headcount Grade 5 IE Level 2"),
    GRADE_05_IE_LEVEL_THREE_COUNT("Headcount Grade 5 IE Level 3"),
    GRADE_05_ELL_COUNT("Headcount Grade 5 ELL"),
    GRADE_05_INDIGENOUS_COUNT("Headcount Grade 5 Indigenous"),
    GRADE_05_CORE_FRENCH_COUNT("Headcount Grade 5 Core French"),
    GRADE_05_EARLY_FRENCH_COUNT("Headcount Grade 5 Early French Immersion"),
    GRADE_05_LATE_FRENCH_COUNT("Headcount Grade 5 Late French Immersion"),

    GRADE_06_IE_LEVEL_ONE_COUNT("Headcount Grade 6 IE Level 1"),
    GRADE_06_IE_LEVEL_TWO_COUNT("Headcount Grade 6 IE Level 2"),
    GRADE_06_IE_LEVEL_THREE_COUNT("Headcount Grade 6 IE Level 3"),
    GRADE_06_ELL_COUNT("Headcount Grade 6 ELL"),
    GRADE_06_INDIGENOUS_COUNT("Headcount Grade 6 Indigenous"),
    GRADE_06_CORE_FRENCH_COUNT("Headcount Grade 6 Core French"),
    GRADE_06_EARLY_FRENCH_COUNT("Headcount Grade 6 Early French Immersion"),
    GRADE_06_LATE_FRENCH_COUNT("Headcount Grade 6 Late French Immersion"),

    GRADE_07_IE_LEVEL_ONE_COUNT("Headcount Grade 7 IE Level 1"),
    GRADE_07_IE_LEVEL_TWO_COUNT("Headcount Grade 7 IE Level 2"),
    GRADE_07_IE_LEVEL_THREE_COUNT("Headcount Grade 7 IE Level 3"),
    GRADE_07_ELL_COUNT("Headcount Grade 7 ELL"),
    GRADE_07_INDIGENOUS_COUNT("Headcount Grade 7 Indigenous"),
    GRADE_07_CORE_FRENCH_COUNT("Headcount Grade 7 Core French"),
    GRADE_07_EARLY_FRENCH_COUNT("Headcount Grade 7 Early French Immersion"),
    GRADE_07_LATE_FRENCH_COUNT("Headcount Grade 7 Late French Immersion"),

    GRADE_08_IE_LEVEL_ONE_COUNT("Headcount Grade 8 IE Level 1"),
    GRADE_08_IE_LEVEL_TWO_COUNT("Headcount Grade 8 IE Level 2"),
    GRADE_08_IE_LEVEL_THREE_COUNT("Headcount Grade 8 IE Level 3"),
    GRADE_08_ELL_COUNT("Headcount Grade 8 ELL"),
    GRADE_08_INDIGENOUS_COUNT("Headcount Grade 8 Indigenous"),
    GRADE_08_CORE_FRENCH_COUNT("Headcount Grade 8 Core French"),
    GRADE_08_EARLY_FRENCH_COUNT("Headcount Grade 8 Early French Immersion"),

    GRADE_09_IE_LEVEL_ONE_COUNT("Headcount Grade 9 IE Level 1"),
    GRADE_09_IE_LEVEL_TWO_COUNT("Headcount Grade 9 IE Level 2"),
    GRADE_09_IE_LEVEL_THREE_COUNT("Headcount Grade 9 IE Level 3"),
    GRADE_09_ELL_COUNT("Headcount Grade 9 ELL"),
    GRADE_09_INDIGENOUS_COUNT("Headcount Grade 9 Indigenous"),
    GRADE_09_CORE_FRENCH_COUNT("Headcount Grade 9 Core French"),
    GRADE_09_EARLY_FRENCH_COUNT("Headcount Grade 9 Early French Immersion"),

    GRADE_10_IE_LEVEL_ONE_COUNT("Headcount Grade 10 IE Level 1"),
    GRADE_10_IE_LEVEL_TWO_COUNT("Headcount Grade 10 IE Level 2"),
    GRADE_10_IE_LEVEL_THREE_COUNT("Headcount Grade 10 IE Level 3"),
    GRADE_10_ELL_COUNT("Headcount Grade 10 ELL"),
    GRADE_10_INDIGENOUS_COUNT("Headcount Grade 10 Indigenous"),
    GRADE_10_CORE_FRENCH_COUNT("Headcount Grade 10 Core French"),
    GRADE_10_EARLY_FRENCH_COUNT("Headcount Grade 10 Early French Immersion"),

    GRADE_11_IE_LEVEL_ONE_COUNT("Headcount Grade 11 IE Level 1"),
    GRADE_11_IE_LEVEL_TWO_COUNT("Headcount Grade 11 IE Level 2"),
    GRADE_11_IE_LEVEL_THREE_COUNT("Headcount Grade 11 IE Level 3"),
    GRADE_11_ELL_COUNT("Headcount Grade 11 ELL"),
    GRADE_11_INDIGENOUS_COUNT("Headcount Grade 11 Indigenous"),
    GRADE_11_CORE_FRENCH_COUNT("Headcount Grade 11 Core French"),
    GRADE_11_EARLY_FRENCH_COUNT("Headcount Grade 11 Early French Immersion"),

    GRADE_12_IE_LEVEL_ONE_COUNT("Headcount Grade 12 IE Level 1"),
    GRADE_12_IE_LEVEL_TWO_COUNT("Headcount Grade 12 IE Level 2"),
    GRADE_12_IE_LEVEL_THREE_COUNT("Headcount Grade 12 IE Level 3"),
    GRADE_12_ELL_COUNT("Headcount Grade 12 ELL"),
    GRADE_12_INDIGENOUS_COUNT("Headcount Grade 12 Indigenous"),
    GRADE_12_CORE_FRENCH_COUNT("Headcount Grade 12 Core French"),
    GRADE_12_EARLY_FRENCH_COUNT("Headcount Grade 12 Early French Immersion"),

    GRADE_EU_IE_LEVEL_ONE_COUNT("Headcount Grade EU IE Level 1"),
    GRADE_EU_IE_LEVEL_TWO_COUNT("Headcount Grade EU IE Level 2"),
    GRADE_EU_IE_LEVEL_THREE_COUNT("Headcount Grade EU IE Level 3"),
    GRADE_EU_ELL_COUNT("Headcount Grade EU ELL"),
    GRADE_EU_INDIGENOUS_COUNT("Headcount Grade EU Indigenous"),
    GRADE_EU_CORE_FRENCH_COUNT("Headcount Grade EU Core French"),
    GRADE_EU_EARLY_FRENCH_COUNT("Headcount Grade EU Early French Immersion"),

    GRADE_SU_IE_LEVEL_ONE_COUNT("Headcount Grade SU IE Level 1"),
    GRADE_SU_IE_LEVEL_TWO_COUNT("Headcount Grade SU IE Level 2"),
    GRADE_SU_IE_LEVEL_THREE_COUNT("Headcount Grade SU IE Level 3"),
    GRADE_SU_ELL_COUNT("Headcount Grade SU ELL"),
    GRADE_SU_INDIGENOUS_COUNT("Headcount Grade SU Indigenous"),
    GRADE_SU_CORE_FRENCH_COUNT("Headcount Grade SU Core French"),
    GRADE_SU_EARLY_FRENCH_COUNT("Headcount Grade SU Early French Immersion"),

    NON_GRAD_ADULT_IE_LEVEL_ONE_COUNT("Headcount Non-Grad Adult IE Level 1"),
    NON_GRAD_ADULT_IE_LEVEL_TWO_COUNT("Headcount Non-Grad Adult IE Level 2"),
    NON_GRAD_ADULT_IE_LEVEL_THREE_COUNT("Headcount Non-Grad Adult IE Level 3"),
    ;

    private final String code;
    EnrolmentAndFteHeader(String code) { this.code = code; }
}
