package ca.bc.gov.educ.studentdatacollection.api.constants.v1.ministryreports;

import lombok.Getter;

@Getter
public enum IndySchoolGradeEnrolmentFundingGroupHeadcountHeader {

    DISTRICT_NUMBER("District Number"),
    SCHOOL_NUMBER("School Number"),
    SCHOOL_NAME("School Name"),
    // Core French
    FUNDING_GROUP_P_CF("Funding Group Primary (K-3) - Core French"),
    FUNDING_GROUP_E_CF("Funding Group Elementary (4-7) - Core French"),
    FUNDING_GROUP_J_CF("Funding Group Jr Secondary (8-10) - Core French"),
    FUNDING_GROUP_S_CF("Funding Group Sr Secondary (11-12) - Core French"),
    FUNDING_GROUP_DL_K9_CF("Distance Learning K-9 - Core French"),
    FUNDING_GROUP_DL_1012_CF("Distance Learning 10-12 - Core French"),
    KIND_HT_CF("KH - Core French"),
    KIND_FT_CF("KF - Core French"),
    GRADE_01_CF("01 - Core French"),
    GRADE_02_CF("02 - Core French"),
    GRADE_03_CF("03 - Core French"),
    GRADE_04_CF("04 - Core French"),
    GRADE_05_CF("05 - Core French"),
    GRADE_06_CF("06 - Core French"),
    GRADE_07_CF("07 - Core French"),
    GRADE_EU_CF("EU - Core French"),
    GRADE_08_CF("08 - Core French"),
    GRADE_09_CF("09 - Core French"),
    GRADE_10_CF("10 - Core French"),
    GRADE_11_CF("11 - Core French"),
    GRADE_12_CF("12 - Core French"),
    GRADE_SU_CF("SU - Core French"),
    GRADE_GA_CF("GA - Core French"),
    TOTAL_CF("Total - Core French"),
    // Programme Francophone
    FUNDING_GROUP_P_PF("Funding Group Primary (K-3) - Programme Francophone"),
    FUNDING_GROUP_E_PF("Funding Group Elementary (4-7) - Programme Francophone"),
    FUNDING_GROUP_J_PF("Funding Group Jr Secondary (8-10) - Programme Francophone"),
    FUNDING_GROUP_S_PF("Funding Group Sr Secondary (11-12) - Programme Francophone"),
    FUNDING_GROUP_DL_K9_PF("Distance Learning K-9 - Programme Francophone"),
    FUNDING_GROUP_DL_1012_PF("Distance Learning 10-12 - Programme Francophone"),
    KIND_HT_PF("KH - Programme Francophone"),
    KIND_FT_PF("KF - Programme Francophone"),
    GRADE_01_PF("01 - Programme Francophone"),
    GRADE_02_PF("02 - Programme Francophone"),
    GRADE_03_PF("03 - Programme Francophone"),
    GRADE_04_PF("04 - Programme Francophone"),
    GRADE_05_PF("05 - Programme Francophone"),
    GRADE_06_PF("06 - Programme Francophone"),
    GRADE_07_PF("07 - Programme Francophone"),
    GRADE_EU_PF("EU - Programme Francophone"),
    GRADE_08_PF("08 - Programme Francophone"),
    GRADE_09_PF("09 - Programme Francophone"),
    GRADE_10_PF("10 - Programme Francophone"),
    GRADE_11_PF("11 - Programme Francophone"),
    GRADE_12_PF("12 - Programme Francophone"),
    GRADE_SU_PF("SU - Programme Francophone"),
    GRADE_GA_PF("GA - Programme Francophone"),
    TOTAL_PF("Total - Programme Francophone"),
    // Early French Immersion
    FUNDING_GROUP_P_EFI("Funding Group Primary (K-3) - Early French Immersion"),
    FUNDING_GROUP_E_EFI("Funding Group Elementary (4-7) - Early French Immersion"),
    FUNDING_GROUP_J_EFI("Funding Group Jr Secondary (8-10) - Early French Immersion"),
    FUNDING_GROUP_S_EFI("Funding Group Sr Secondary (11-12) - Early French Immersion"),
    FUNDING_GROUP_DL_K9_EFI("Distance Learning K-9 - Early French Immersion"),
    FUNDING_GROUP_DL_1012_EFI("Distance Learning 10-12 - Early French Immersion"),
    KIND_HT_EFI("KH - Early French Immersion"),
    KIND_FT_EFI("KF - Early French Immersion"),
    GRADE_01_EFI("01 - Early French Immersion"),
    GRADE_02_EFI("02 - Early French Immersion"),
    GRADE_03_EFI("03 - Early French Immersion"),
    GRADE_04_EFI("04 - Early French Immersion"),
    GRADE_05_EFI("05 - Early French Immersion"),
    GRADE_06_EFI("06 - Early French Immersion"),
    GRADE_07_EFI("07 - Early French Immersion"),
    GRADE_EU_EFI("EU - Early French Immersion"),
    GRADE_08_EFI("08 - Early French Immersion"),
    GRADE_09_EFI("09 - Early French Immersion"),
    GRADE_10_EFI("10 - Early French Immersion"),
    GRADE_11_EFI("11 - Early French Immersion"),
    GRADE_12_EFI("12 - Early French Immersion"),
    GRADE_SU_EFI("SU - Early French Immersion"),
    GRADE_GA_EFI("GA - Early French Immersion"),
    TOTAL_EFI("Total - Early French Immersion"),
    // Late French Immersion
    FUNDING_GROUP_P_LFI("Funding Group Primary (K-3) - Late French Immersion"),
    FUNDING_GROUP_E_LFI("Funding Group Elementary (4-7) - Late French Immersion"),
    FUNDING_GROUP_J_LFI("Funding Group Jr Secondary (8-10) - Late French Immersion"),
    FUNDING_GROUP_S_LFI("Funding Group Sr Secondary (11-12) - Late French Immersion"),
    FUNDING_GROUP_DL_K9_LFI("Distance Learning K-9 - Late French Immersion"),
    FUNDING_GROUP_DL_1012_LFI("Distance Learning 10-12 - Late French Immersion"),
    KIND_HT_LFI("KH - Late French Immersion"),
    KIND_FT_LFI("KF - Late French Immersion"),
    GRADE_01_LFI("01 - Late French Immersion"),
    GRADE_02_LFI("02 - Late French Immersion"),
    GRADE_03_LFI("03 - Late French Immersion"),
    GRADE_04_LFI("04 - Late French Immersion"),
    GRADE_05_LFI("05 - Late French Immersion"),
    GRADE_06_LFI("06 - Late French Immersion"),
    GRADE_07_LFI("07 - Late French Immersion"),
    GRADE_EU_LFI("EU - Late French Immersion"),
    GRADE_08_LFI("08 - Late French Immersion"),
    GRADE_09_LFI("09 - Late French Immersion"),
    GRADE_10_LFI("10 - Late French Immersion"),
    GRADE_11_LFI("11 - Late French Immersion"),
    GRADE_12_LFI("12 - Late French Immersion"),
    GRADE_SU_LFI("SU - Late French Immersion"),
    GRADE_GA_LFI("GA - Late French Immersion"),
    TOTAL_LFI("Total - Late French Immersion"),
    // English Language Learning
    FUNDING_GROUP_P_ELL("Funding Group Primary (K-3) - English Language Learning"),
    FUNDING_GROUP_E_ELL("Funding Group Elementary (4-7) - English Language Learning"),
    FUNDING_GROUP_J_ELL("Funding Group Jr Secondary (8-10) - English Language Learning"),
    FUNDING_GROUP_S_ELL("Funding Group Sr Secondary (11-12) - English Language Learning"),
    FUNDING_GROUP_DL_K9_ELL("Distance Learning K-9 - English Language Learning"),
    FUNDING_GROUP_DL_1012_ELL("Distance Learning 10-12 - English Language Learning"),
    KIND_HT_ELL("KH - English Language Learning"),
    KIND_FT_ELL("KF - English Language Learning"),
    GRADE_01_ELL("01 - English Language Learning"),
    GRADE_02_ELL("02 - English Language Learning"),
    GRADE_03_ELL("03 - English Language Learning"),
    GRADE_04_ELL("04 - English Language Learning"),
    GRADE_05_ELL("05 - English Language Learning"),
    GRADE_06_ELL("06 - English Language Learning"),
    GRADE_07_ELL("07 - English Language Learning"),
    GRADE_EU_ELL("EU - English Language Learning"),
    GRADE_08_ELL("08 - English Language Learning"),
    GRADE_09_ELL("09 - English Language Learning"),
    GRADE_10_ELL("10 - English Language Learning"),
    GRADE_11_ELL("11 - English Language Learning"),
    GRADE_12_ELL("12 - English Language Learning"),
    GRADE_SU_ELL("SU - English Language Learning"),
    GRADE_GA_ELL("GA - English Language Learning"),
    TOTAL_ELL("Total - English Language Learning"),
    // Indigenous Language and Culture
    FUNDING_GROUP_P_ALC("Funding Group Primary (K-3) - Indigenous Language and Culture"),
    FUNDING_GROUP_E_ALC("Funding Group Elementary (4-7) - Indigenous Language and Culture"),
    FUNDING_GROUP_J_ALC("Funding Group Jr Secondary (8-10) - Indigenous Language and Culture"),
    FUNDING_GROUP_S_ALC("Funding Group Sr Secondary (11-12) - Indigenous Language and Culture"),
    FUNDING_GROUP_DL_K9_ALC("Distance Learning K-9 - Indigenous Language and Culture"),
    FUNDING_GROUP_DL_1012_ALC("Distance Learning 10-12 - Indigenous Language and Culture"),
    KIND_HT_ALC("KH - Indigenous Language and Culture"),
    KIND_FT_ALC("KF - Indigenous Language and Culture"),
    GRADE_01_ALC("01 - Indigenous Language and Culture"),
    GRADE_02_ALC("02 - Indigenous Language and Culture"),
    GRADE_03_ALC("03 - Indigenous Language and Culture"),
    GRADE_04_ALC("04 - Indigenous Language and Culture"),
    GRADE_05_ALC("05 - Indigenous Language and Culture"),
    GRADE_06_ALC("06 - Indigenous Language and Culture"),
    GRADE_07_ALC("07 - Indigenous Language and Culture"),
    GRADE_EU_ALC("EU - Indigenous Language and Culture"),
    GRADE_08_ALC("08 - Indigenous Language and Culture"),
    GRADE_09_ALC("09 - Indigenous Language and Culture"),
    GRADE_10_ALC("10 - Indigenous Language and Culture"),
    GRADE_11_ALC("11 - Indigenous Language and Culture"),
    GRADE_12_ALC("12 - Indigenous Language and Culture"),
    GRADE_SU_ALC("SU - Indigenous Language and Culture"),
    GRADE_GA_ALC("GA - Indigenous Language and Culture"),
    TOTAL_ALC("Total - Indigenous Language and Culture"),
    // Indigenous Support Services
    FUNDING_GROUP_P_ASS("Funding Group Primary (K-3) - Indigenous Support Services"),
    FUNDING_GROUP_E_ASS("Funding Group Elementary (4-7) - Indigenous Support Services"),
    FUNDING_GROUP_J_ASS("Funding Group Jr Secondary (8-10) - Indigenous Support Services"),
    FUNDING_GROUP_S_ASS("Funding Group Sr Secondary (11-12) - Indigenous Support Services"),
    FUNDING_GROUP_DL_K9_ASS("Distance Learning K-9 - Indigenous Support Services"),
    FUNDING_GROUP_DL_1012_ASS("Distance Learning 10-12 - Indigenous Support Services"),
    KIND_HT_ASS("KH - Indigenous Support Services"),
    KIND_FT_ASS("KF - Indigenous Support Services"),
    GRADE_01_ASS("01 - Indigenous Support Services"),
    GRADE_02_ASS("02 - Indigenous Support Services"),
    GRADE_03_ASS("03 - Indigenous Support Services"),
    GRADE_04_ASS("04 - Indigenous Support Services"),
    GRADE_05_ASS("05 - Indigenous Support Services"),
    GRADE_06_ASS("06 - Indigenous Support Services"),
    GRADE_07_ASS("07 - Indigenous Support Services"),
    GRADE_EU_ASS("EU - Indigenous Support Services"),
    GRADE_08_ASS("08 - Indigenous Support Services"),
    GRADE_09_ASS("09 - Indigenous Support Services"),
    GRADE_10_ASS("10 - Indigenous Support Services"),
    GRADE_11_ASS("11 - Indigenous Support Services"),
    GRADE_12_ASS("12 - Indigenous Support Services"),
    GRADE_SU_ASS("SU - Indigenous Support Services"),
    GRADE_GA_ASS("GA - Indigenous Support Services"),
    TOTAL_ASS("Total - Indigenous Support Services"),
    // Other Approved Indigenous Programs
    FUNDING_GROUP_P_OAAP("Funding Group Primary (K-3) - Other Approved Indigenous Programs"),
    FUNDING_GROUP_E_OAAP("Funding Group Elementary (4-7) - Other Approved Indigenous Programs"),
    FUNDING_GROUP_J_OAAP("Funding Group Jr Secondary (8-10) - Other Approved Indigenous Programs"),
    FUNDING_GROUP_S_OAAP("Funding Group Sr Secondary (11-12) - Other Approved Indigenous Programs"),
    FUNDING_GROUP_DL_K9_OAAP("Distance Learning K-9 - Other Approved Indigenous Programs"),
    FUNDING_GROUP_DL_1012_OAAP("Distance Learning 10-12 - Other Approved Indigenous Programs"),
    KIND_HT_OAAP("KH - Other Approved Indigenous Programs"),
    KIND_FT_OAAP("KF - Other Approved Indigenous Programs"),
    GRADE_01_OAAP("01 - Other Approved Indigenous Programs"),
    GRADE_02_OAAP("02 - Other Approved Indigenous Programs"),
    GRADE_03_OAAP("03 - Other Approved Indigenous Programs"),
    GRADE_04_OAAP("04 - Other Approved Indigenous Programs"),
    GRADE_05_OAAP("05 - Other Approved Indigenous Programs"),
    GRADE_06_OAAP("06 - Other Approved Indigenous Programs"),
    GRADE_07_OAAP("07 - Other Approved Indigenous Programs"),
    GRADE_EU_OAAP("EU - Other Approved Indigenous Programs"),
    GRADE_08_OAAP("08 - Other Approved Indigenous Programs"),
    GRADE_09_OAAP("09 - Other Approved Indigenous Programs"),
    GRADE_10_OAAP("10 - Other Approved Indigenous Programs"),
    GRADE_11_OAAP("11 - Other Approved Indigenous Programs"),
    GRADE_12_OAAP("12 - Other Approved Indigenous Programs"),
    GRADE_SU_OAAP("SU - Other Approved Indigenous Programs"),
    GRADE_GA_OAAP("GA - Other Approved Indigenous Programs"),
    TOTAL_OAAP("Total - Other Approved Indigenous Programs"),
    ;

    private final String code;
    IndySchoolGradeEnrolmentFundingGroupHeadcountHeader(String code) { this.code = code; }
}

