package ca.bc.gov.educ.studentdatacollection.api.filter;

import ca.bc.gov.educ.studentdatacollection.api.model.v1.SdcSchoolCollectionStudentPaginationShallowEntity;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.chrono.ChronoLocalDate;
import java.time.chrono.ChronoLocalDateTime;
import java.util.UUID;

@Service
@Slf4j
public class SdcSchoolCollectionStudentShallowFilterSpecs extends BaseFilterSpecs<SdcSchoolCollectionStudentPaginationShallowEntity> {

  public SdcSchoolCollectionStudentShallowFilterSpecs(FilterSpecifications<SdcSchoolCollectionStudentPaginationShallowEntity, ChronoLocalDate> dateFilterSpecifications, FilterSpecifications<SdcSchoolCollectionStudentPaginationShallowEntity, ChronoLocalDateTime<?>> dateTimeFilterSpecifications, FilterSpecifications<SdcSchoolCollectionStudentPaginationShallowEntity, Integer> integerFilterSpecifications, FilterSpecifications<SdcSchoolCollectionStudentPaginationShallowEntity, String> stringFilterSpecifications, FilterSpecifications<SdcSchoolCollectionStudentPaginationShallowEntity, Long> longFilterSpecifications, FilterSpecifications<SdcSchoolCollectionStudentPaginationShallowEntity, UUID> uuidFilterSpecifications, FilterSpecifications<SdcSchoolCollectionStudentPaginationShallowEntity, Boolean> booleanFilterSpecifications, Converters converters) {
    super(dateFilterSpecifications, dateTimeFilterSpecifications, integerFilterSpecifications, stringFilterSpecifications, longFilterSpecifications, uuidFilterSpecifications, booleanFilterSpecifications, converters);
  }
}
